### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by lrtal** [krzychb/esp-epaper-29-ws#1]
Arduino: 1.8.5 (Windows 10), Board: "ESP32 Dev Module, Default, QIO, 80MHz, 4MB (32Mb), 115200, None"

epd2in9-demo:30: error: stray '\302' in program

   <title>esp-epaper-29-ws/epd2in9-demo.ino at master ֲ· krzychb/esp-epaper-29-ws</title>

   ^

epd2in9-demo:30: error: stray '\267' in program

epd2in9-demo:143: error: missing terminating ' character

     </option></form><form class="js-site-search-form" data-scope-type="Repository" data-scope-id="115144223" data-scoped-search-url="/krzychb/esp-epaper-29-ws/search" data-unscoped-search-url="/search" action="/krzychb/esp-epaper-29-ws/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />

     ^

epd2in9-demo:180: error: stray '\342' in program

                       <span aria-hidden="true" class="d-inline-block ml-1 v-align-middle">ג†µ</span>

                       ^

epd2in9-demo:180: error: stray '\206' in program

epd2in9-demo:180: error: stray '\265' in program

epd2in9-demo:185: error: stray '\342' in program

                       <span class="d-inline-block ml-1 v-align-middle">ג†µ</span>

                       ^

epd2in9-demo:185: error: stray '\206' in program

epd2in9-demo:185: error: stray '\265' in program

epd2in9-demo:320: error: missing terminating ' character

         <li></option></form><form class="logout-form" action="/logout" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="vMaMppAWxYfKNTnrUP0whuSy4KdAe89M7HIhEyMxP5LQioQPrrDdilKd/qyXRyPAr2q0IVZuB1/2/G116OR6sQ==" />

         ^

epd2in9-demo:332: error: missing terminating ' character

         </option></form><form class="sr-only right-0" action="/logout" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="XCcwfC1LYXZNhxo/SlWIKalvZdcJCECmh4NqyiVYWvEwazjVE+15e9Uv3XiN75tv4rcxUR8diLWdDSas7o0f0g==" />

         ^

epd2in9-demo:368: error: missing terminating ' character

         </option></form><form data-autosubmit="true" data-remote="true" class="js-social-container" action="/notifications/subscribe" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="qrB1KVCgGwalgJ+kADxGF0ONLLC1CwCPooCTTuSOlKhxgP+elsY10FEArVwbSPMK50hKHrk8sjUkkZs1PJreIw==" />      <input type="hidden" name="repository_id" id="repository_id" value="115144223" class="form-control" />

         ^

epd2in9-demo:403: error: stray '@' in program

                     <span class="description">Be notified when participating or @mentioned.</span>

                                                                                 ^

epd2in9-demo:448: error: missing terminating ' character

     </option></form><form class="starred js-social-form" action="/krzychb/esp-epaper-29-ws/unstar" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="ap4aix93u7Ejfb4Ch74z8zlrBJeSzYiD23XRWVOAMg8/IPtGnIuNtuEFUUS4FVcbwaY37vmxp2/X7qZIP1XeqA==" />

     ^

epd2in9-demo:463: error: missing terminating ' character

     </option></form><form class="unstarred js-social-form" action="/krzychb/esp-epaper-29-ws/star" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="tiJU8CW+/W6G0gVWYYYnNuqyAWkKh9v0Kc8BNEq5W2nKOWJhN8/vIq7GN26IReEl81u7wMzbf5wVuXUbCHkO7A==" />

     ^

epd2in9-demo:482: error: missing terminating ' character

           </option></form><form class="btn-with-count" action="/krzychb/esp-epaper-29-ws/fork" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="7qp/fWHbULuJDhsa5JCBTK6r4lr55CtEqjfA+bxL1x7LPw8hOD2IbiLKIlwUsGz5TM3BadoIbo5rYlVSZx2ZxA==" />

           ^

epd2in9-demo:702: error: missing terminating ' character

           </option></form><form class="inline-form js-update-url-with-hash" action="/krzychb/esp-epaper-29-ws/edit/master/Arduino/epd2in9-demo/epd2in9-demo.ino" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="OFpMykRb7txZf1AHCG5PvsasKfeA7VP0lcn6wGNtUeLGGuRKMZsMvOzLG/H9AzqPArUvT0+oG83NQlbci7bNZw==" />

           ^

epd2in9-demo:708: error: missing terminating ' character

         </option></form><form class="inline-form" action="/krzychb/esp-epaper-29-ws/delete/master/Arduino/epd2in9-demo/epd2in9-demo.ino" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="LQCdh9g2kr5wIqYjV5reGweZXMhMgBY+MUC/LSI+y4KM9/hBK2DlrUySFfIvK2CYb0/2KVDtnBNYVZmJhlKK5Q==" />

         ^

epd2in9-demo:841: error: stray '#' in program

         <td id="LC29" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>SPI.h<span class="pl-pds">&gt;</span></span></td>

                                                                      ^

epd2in9-demo:845: error: stray '#' in program

         <td id="LC30" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epd2in9.h<span class="pl-pds">&gt;</span></span></td>

                                                                      ^

epd2in9-demo:849: error: stray '#' in program

         <td id="LC31" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epdpaint.h<span class="pl-pds">&gt;</span></span></td>

                                                                      ^

epd2in9-demo:853: error: stray '#' in program

         <td id="LC32" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&quot;</span>imagedata.h<span class="pl-pds">&quot;</span></span></td>

                                                                      ^

epd2in9-demo:862: error: stray '#' in program

         <td id="LC34" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">define</span> <span class="pl-en">COLORED</span>     <span class="pl-c1">0</span></td>

                                                                      ^

epd2in9-demo:866: error: stray '#' in program

         <td id="LC35" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">define</span> <span class="pl-en">UNCOLORED</span>   <span class="pl-c1">1</span></td>

                                                                      ^

epd2in9-demo:1087: error: missing terminating ' character

     </option></form><form class="js-jump-to-line-form" action="" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />

     ^

epd2in9-demo:1139: error: stray '\342' in program

     You canג€™t perform that action at this time.

     ^

epd2in9-demo:1139: error: stray '\200' in program

epd2in9-demo:1139: error: stray '\231' in program

epd2in9-demo:7: error: expected unqualified-id before '<' token

 <!DOCTYPE html>

 ^

epd2in9-demo:841: error: expected unqualified-id before '<' token

         <td id="LC29" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>SPI.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                     ^

epd2in9-demo:841: error: expected unqualified-id before '<' token

         <td id="LC29" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>SPI.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                                                          ^

epd2in9-demo:845: error: expected unqualified-id before '<' token

         <td id="LC30" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epd2in9.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                     ^

epd2in9-demo:845: error: expected unqualified-id before '<' token

         <td id="LC30" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epd2in9.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                                                              ^

epd2in9-demo:849: error: expected unqualified-id before '<' token

         <td id="LC31" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epdpaint.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                     ^

epd2in9-demo:849: error: expected unqualified-id before '<' token

         <td id="LC31" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>epdpaint.h<span class="pl-pds">&gt;</span></span></td>

                                                                                                                                                                                               ^

epd2in9-demo:853: error: expected unqualified-id before '<' token

         <td id="LC32" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&quot;</span>imagedata.h<span class="pl-pds">&quot;</span></span></td>

                                                                                                                                                       ^

epd2in9-demo:853: error: expected unqualified-id before '<' token

         <td id="LC32" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&quot;</span>imagedata.h<span class="pl-pds">&quot;</span></span></td>

                                                                                                                                                                                                    ^

epd2in9-demo:875: error: expected unqualified-id before '<' token

         <td id="LC37" class="blob-code blob-code-inner js-file-line"><span class="pl-k">unsigned</span> <span class="pl-k">char</span> image[<span class="pl-c1">4736</span>];</td>

                                                                                                                                                                               ^

epd2in9-demo:879: error: expected unqualified-id before '<' token

         <td id="LC38" class="blob-code blob-code-inner js-file-line">Paint <span class="pl-en">paint</span>(image, <span class="pl-c1">0</span>, <span class="pl-c1">0</span>);    <span class="pl-c"><span class="pl-c">//</span> width should be the multiple of 8 </span></td>

                                                                                                                                                                                    ^

epd2in9-demo:883: error: expected unqualified-id before '<' token

         <td id="LC39" class="blob-code blob-code-inner js-file-line">Epd epd;</td>

                                                                              ^

exit status 1
stray '\302' in program

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by krzychb** [comment]
Hi @lrtal from the log it looks like you are trying to compile some file with HTML tags instead of a file with c source code.

**Comment by lrtal** [comment]
hello, yes i copied it from raw and now its ok   . thank you

**Comment by krzychb** [comment]
Thanks for update
